#!/bin/bash
g++ -O3 iter.cpp
i=0;
while true
do
    cat input1.txt out1.txt > in1.txt
    cat input2.txt out2.txt > in2.txt
    cat input3.txt out3.txt > in3.txt
    cat input4.txt out4.txt > in4.txt
    cat input5.txt out5.txt > in5.txt
    ./a.out< in1.txt > out1.txt
    ./a.out< in2.txt > out2.txt
    ./a.out< in3.txt > out3.txt
    ./a.out< in4.txt > out4.txt
    ./a.out< in5.txt > out5.txt
    i=$((i+1));
    echo $i;
done